# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouEE30OJHZ6SG_QjgpC9ZBBg5ovlPFJb
"""

import torch
import torch.nn as nn
import math
MODEL_PATH = "/content/final_model.pth"
import wandb
wandb.init(project="gpt-language-model", config={
    "batch_size": 64,
    "block_size": 256,
    "n_embd": 384,
    "n_head": 6,
    "n_layer": 6,
    "dropout": 0.2,
    "learning_rate": 5e-5,
    "max_iters": 5000,
    "eval_interval": 500,
    "eval_iters": 200,  # Add this missing parameter
    "device": "cuda" if torch.cuda.is_available() else "cpu"
})
config = wandb.config

class SinusoidalPositionalEmbedding(nn.Module):
    def __init__(self, embedding_dim, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, embedding_dim)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, embedding_dim, 2) * -(math.log(10000.0) / embedding_dim))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer("pe", pe)

    def forward(self, x):
        return x + self.pe[:x.size(1)]

# Attention Head
class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(config.n_embd, head_size, bias=False)
        self.query = nn.Linear(config.n_embd, head_size, bias=False)
        self.value = nn.Linear(config.n_embd, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(config.block_size, config.block_size)))
        self.dropout = nn.Dropout(config.dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2, -1) * k.shape[-1] ** -0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf"))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        return wei @ v

# Multi-Head Attention
class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, config.n_embd)
        self.dropout = nn.Dropout(config.dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))

# Feed-Forward Network
class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(config.dropout),
        )

    def forward(self, x):
        return self.net(x)

# Transformer Block
class Block(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


class GPTLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, config.n_embd)
        self.position_embedding = SinusoidalPositionalEmbedding(config.n_embd)
        self.blocks = nn.Sequential(*[Block(config.n_embd, config.n_head) for _ in range(config.n_layer)])
        self.ln_f = nn.LayerNorm(config.n_embd)
        self.lm_head = nn.Linear(config.n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.xavier_uniform_(module.weight)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding(tok_emb)
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        loss = None
        if targets is not None:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens, temperature=1.0, top_k=10):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -config.block_size:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :] / temperature
            probs = F.softmax(logits, dim=-1)
            probs, indices = probs.topk(top_k, dim=-1)
            probs = probs / probs.sum(dim=-1, keepdim=True)
            idx_next = indices.gather(-1, torch.multinomial(probs, 1))
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

vocab_size = 65

model = GPTLanguageModel(vocab_size).to("cpu")
model.load_state_dict(torch.load(MODEL_PATH, map_location="cpu"))
model.eval()

# Dynamic Quantization
quantized_model = torch.quantization.quantize_dynamic(
    model,  # Original model
    {nn.Linear, nn.LSTM, nn.GRU},  # Layers to quantize
    dtype=torch.qint8  # Quantized data type
)

# Save the Quantized Model
quantized_model_save_path = "/content/quantized_model.pth"
torch.save(quantized_model.state_dict(), quantized_model_save_path)
print(f"Quantized model saved to {quantized_model_save_path}")

# Reload the Quantized Model
loaded_quantized_model = GPTLanguageModel(vocab_size).to(config.device)
loaded_quantized_model = torch.quantization.quantize_dynamic(
    loaded_quantized_model,
    {nn.Linear, nn.LSTM, nn.GRU},
    dtype=torch.qint8
)
loaded_quantized_model.load_state_dict(torch.load(quantized_model_save_path))
loaded_quantized_model.eval()

print("Quantized model reloaded and ready for inference.")

# Import your model definition
import torch.nn.functional as F
# Define paths
VOCAB_PATH = "/content/vocab_info.pth"
QUANTIZED_MODEL_PATH = "/content/quantized_model.pth"

# Load the vocabulary
print("Loading vocabulary...")
vocab = torch.load(VOCAB_PATH)
stoi = vocab["stoi"]
itos = vocab["itos"]
vocab_size = len(stoi)

# Rebuild the quantized model
print("Rebuilding the quantized model...")
model = GPTLanguageModel(vocab_size).to("cpu")
quantized_model = torch.quantization.quantize_dynamic(
    model,  # Same model structure
    {torch.nn.Linear},  # Layers that were quantized
    dtype=torch.qint8
)

# Load the quantized model state
quantized_model.load_state_dict(torch.load(QUANTIZED_MODEL_PATH, map_location="cpu"))
quantized_model.eval()
print("Quantized model loaded successfully!")

# Test inference
print("Running inference with the quantized model...")
context = torch.zeros((1, 1), dtype=torch.long)  # Start with a single token
generated_text = "".join([itos[i] for i in quantized_model.generate(context, max_new_tokens=100)[0].tolist()])
print("Generated Text:")
print(generated_text)

# Additional Evaluation
print("Evaluating the quantized model...")
sample_input = "hello world"
encoded_input = torch.tensor([[stoi[c] for c in sample_input if c in stoi]], dtype=torch.long)
with torch.no_grad():
    logits, _ = quantized_model(encoded_input)
    predicted_ids = logits.argmax(dim=-1).squeeze().tolist()
    predicted_text = "".join([itos[i] for i in predicted_ids if i in itos])

print(f"Input: {sample_input}")
print(f"Predicted Output: {predicted_text}")

# Count the number of parameters in the quantized model
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

# Example usage with the quantized model
num_params = count_parameters(quantized_model)
print(f"Number of parameters in the quantized model: {num_params}")
